---
trust-domain: "bedrock"
task-priority: low

taskgraph:
  cached-task-prefix: "bedrock.v2.bedrock"
  repositories:
    bedrock:
      name: "bedrock"

workers:
  aliases:
    b-linux:
      provisioner: '{trust-domain}-{level}'
      implementation: docker-worker
      os: linux
      worker-type: '{alias}-gcp'
    images:
      provisioner: '{trust-domain}-{level}'
      implementation: docker-worker
      os: linux
      worker-type: '{alias}-gcp'
    t-linux-large:
      provisioner: '{trust-domain}-t'
      implementation: docker-worker
      os: linux
      worker-type: '{alias}-gcp'
